jwt:
  header: Authorization
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd6eXoxMjMxMjMxMjMxMjMxMjMxMzEyMzEyMzEzMTIzMTIzMTIzMTMxMjMxMzEzMTMxMjM

spring:
  datasource:
    url: jdbc:postgresql://db-toucheese-2.cja2kuiisy1n.ap-northeast-2.rds.amazonaws.com/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST} 
      port: ${REDIS_PORT}

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: toucheese-team2-s3

  mail:
    host: smtp.gmail.com
    port: 587
    username: toucheesebe@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  packages-to-scan: com.example.toucheese_be
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API docs
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-consumes-media-type: application/json;charset=UTF-8